# Change these first
owner: 20xlevel # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  # - name: Price API
  #   url: https://api.level.finance/health
  - name: BSC keeper balance
    url: https://keeper-mainnet.herokuapp.com/health/executor
  - name: BSC price feed
    url: https://keeper-mainnet.herokuapp.com/health/price-feed
  - name: BSC farm fund
    url: https://keeper-mainnet.herokuapp.com/health/level-master
  # - name: AR balance
  #   url: https://api.level.finance/health/arbalance 
  - name: Order expire rate
    url: https://keeper-mainnet.herokuapp.com/health/expire-rate
  
  - name: Terminal API
    url: https://terminal.level.finance/v4/health
  - name: Terminal Worker
    url: https://terminal.level.finance/v4/worker/health


# runner: "[self-hosted, linux, x64]"

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  theme: dark
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/level-fi/assets/main/LVL.png
  name: LevelFinance
  introTitle: LevelFinance
  introMessage: "A Decentralized Perpetual Exchange with Functional Risk Management and Innovative Liquidity Solutions."
  navbar:
    - title: LevelFinance Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
